config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'student#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      redirect_to @student
    else
      render :edit
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:name, :course)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentUnion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>

  <div>
    <%= f.label(:course) %>
    <%= f.text_field(:course) %>
  </div>
  
  <div>
    <%= f.submit('Save Student') %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %></h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1>Student List</h1>

<ul>
  <% @students.each do |student| %>
    <li><%= student.name %> | <%= student.course %> <%= link_to 'Delete', student, method: :delete %> <%= link_to 'Edit', student, method: :edit %></li>
  <% end %>
</ul>

<%= link_to 'Add a new student', new_student_path %>

app/views/students/new.html.erb
<h1>Add a new student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<h1>Student <%= @student.name %></h1>

<p><%= @student.name %> is signed up for <%= @student.course %>.</p>

<%= link_to 'Go back to All Student List', students_path %>